spring:
  activemq:
    broker-url: tcp://localhost:61616
    packages:
      trusted: "com.example"

  jms:
    pubSubDomain: true    #to retrieve the message from topic(as default its queue)

#listener:   #not required
#  auto-startup: true